apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - tunnel.yaml
  - gateway.yaml
  - dns.yaml
  - accesspolicy.yaml
  - referencegrant.yaml
  - services.yaml
  - httproutes.yaml
