apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - namespace.yaml
  - tunnel.yaml
  - gateway.yaml
  - dnssync.yaml
  - services.yaml
  - httproutes.yaml
